Traceback (most recent call last):
  File "/Users/df/anaconda3/envs/ml/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/df/anaconda3/envs/ml/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/df/anaconda3/envs/ml/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/df/anaconda3/envs/ml/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/df/anaconda3/envs/ml/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/df/anaconda3/envs/ml/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/df/anaconda3/envs/ml/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
cases = [chr(c) for c in list(range(8592, 9251)) + [
  63743,
]] + [
  '\u002D',
  '\u2013',
  '\u2014',
  '\u2060', # replaces U+FEFF qua deprecated ZERO WIDTH NO-BREAK SPACE
  '\uFEFF', # BOM
  '\uFFEF', # BOM, byte-swapped (illegal sequence that may not appear in Unicode text)
  #string.printable,
]
print_code_point_information(cases)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 12[0m
[1;32m      1[0m cases [38;5;241m=[39m [[38;5;28mchr[39m(c) [38;5;28;01mfor[39;00m c [38;5;129;01min[39;00m [38;5;28mlist[39m([38;5;28mrange[39m([38;5;241m8592[39m, [38;5;241m9251[39m)) [38;5;241m+[39m [
[1;32m      2[0m   [38;5;241m63743[39m,
[1;32m      3[0m ]] [38;5;241m+[39m [
[0;32m   (...)[0m
[1;32m     10[0m   [38;5;66;03m#string.printable,[39;00m
[1;32m     11[0m ]
[0;32m---> 12[0m [43mprint_code_point_information[49m(cases)

[0;31mNameError[0m: name 'print_code_point_information' is not defined

